/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus which simulator we are talking to.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description What the active adapter supports. The UI disables the rest.
         */
        get: operations["capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * State
         * @description One snapshot of the user aircraft.
         */
        get: operations["state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aircraft/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aircraft Controls
         * @description Which Aircraft Control panel controls are writable, and why the rest are not.
         *
         *     The panel renders every control in this list. Entries with
         *     ``supported = false`` render disabled, showing ``reason`` — the UI never
         *     calls an endpoint the adapter cannot honour and never catches a failure
         *     it could have prevented.
         */
        get: operations["aircraft_controls_api_aircraft_controls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aircraft/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Aircraft Setup
         * @description Apply every field of ``setup`` that is set, leaving the rest untouched.
         *
         *     Idempotent: the body states target values, not deltas, so replaying it is
         *     harmless. Any field whose control is unsupported is refused as a whole
         *     with ``501`` and a stated reason rather than partially applied.
         */
        post: operations["apply_aircraft_setup_api_aircraft_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AircraftControlManifest
         * @description The full control catalogue, resolved against the active adapter.
         */
        AircraftControlManifest: {
            /**
             * Adapter
             * @description Name of the adapter the manifest was resolved against.
             */
            adapter: string;
            /**
             * Controls
             * @description One entry per panel control.
             */
            controls: components["schemas"]["AircraftControlSupport"][];
        };
        /**
         * AircraftControlSupport
         * @description Whether one panel control is writable right now — and why not, when it is not.
         *
         *     This is hard rule 3 ("capabilities, not failures") made specific enough for a
         *     UI to act on: a raw capability flag says the adapter can drive an autopilot,
         *     it does not say the server has a field to carry the request. Both have to be
         *     true, and the panel needs to tell the instructor which one is missing.
         */
        AircraftControlSupport: {
            /**
             * Control
             * @description Panel control identifier.
             * @enum {string}
             */
            control: "flaps" | "speedbrake" | "gear" | "autobrake" | "trim" | "lights" | "altitude" | "speed" | "vertical_speed" | "heading" | "autopilot_master" | "autopilot_nav" | "autopilot_app" | "autopilot_hdg" | "flight_director" | "target_altitude" | "target_speed" | "target_heading" | "target_vertical_speed";
            /**
             * Setup Field
             * @description The AircraftSetup field this control writes.
             */
            setup_field: string;
            /**
             * Capability
             * @description Capability flag the adapter must declare.
             */
            capability: string;
            /**
             * Supported
             * @description True when the control may be written.
             */
            supported: boolean;
            /**
             * Reason
             * @description Why the control is disabled. None when supported.
             */
            reason?: string | null;
        };
        /**
         * AircraftSetup
         * @description The "configure before teleport" payload.
         *
         *     Every field is optional: ``None`` means *leave that aspect of the aircraft
         *     untouched*. An adapter must apply exactly the fields that are set and must
         *     not reset the others to a default.
         *
         *     **This model is the whole write surface of the aircraft**, autopilot
         *     included. There is deliberately no separate ``set_autopilot`` seam on
         *     :class:`~core.sim_adapter.SimAdapter`: an instructor arming HDG and dialling
         *     the heading bug is one intent, and splitting it across two calls would make
         *     it two half-applied states an aircraft can be caught between. The fields are
         *     still gated separately — the autopilot block needs
         *     :attr:`~core.sim_adapter.Capabilities.can_control_autopilot`, everything else
         *     needs ``can_set_aircraft_state`` — so an adapter that cannot drive an
         *     autopilot refuses those fields and honours the rest.
         */
        AircraftSetup: {
            /**
             * Altitude Ft
             * @description Feet above mean sea level.
             */
            altitude_ft?: number | null;
            /**
             * Ias Kt
             * @description Indicated airspeed in knots.
             */
            ias_kt?: number | null;
            /**
             * Vertical Speed Fpm
             * @description Feet per minute.
             */
            vertical_speed_fpm?: number | null;
            /**
             * Heading Deg
             * @description True heading in degrees.
             */
            heading_deg?: number | null;
            /**
             * Pitch Deg
             * @description Degrees, positive nose up.
             */
            pitch_deg?: number | null;
            /**
             * Roll Deg
             * @description Degrees, positive right wing down.
             */
            roll_deg?: number | null;
            /**
             * Gross Weight Kg
             * @description Total aircraft mass in kilograms.
             */
            gross_weight_kg?: number | null;
            /**
             * Fuel Kg
             * @description Total fuel in kilograms.
             */
            fuel_kg?: number | null;
            /**
             * Flaps Ratio
             * @description 0 = up, 1 = fully deployed.
             */
            flaps_ratio?: number | null;
            /**
             * Speedbrake Ratio
             * @description 0 = retracted, 1 = fully deployed.
             */
            speedbrake_ratio?: number | null;
            /**
             * Elevator Trim Ratio
             * @description -1 = full nose down, 0 = neutral, +1 = full nose up.
             */
            elevator_trim_ratio?: number | null;
            /**
             * Gear Down
             * @description True = gear down and locked.
             */
            gear_down?: boolean | null;
            /**
             * Autobrake Level
             * @description 0 = off, increasing = stronger deceleration.
             */
            autobrake_level?: number | null;
            /** @description Exterior light switches. */
            lights?: components["schemas"]["LightsSetup"] | null;
            /**
             * Nav1 Freq Khz
             * @description NAV1 frequency in kHz.
             */
            nav1_freq_khz?: number | null;
            /**
             * Nav2 Freq Khz
             * @description NAV2 frequency in kHz.
             */
            nav2_freq_khz?: number | null;
            /**
             * Ils Freq Khz
             * @description ILS frequency in kHz.
             */
            ils_freq_khz?: number | null;
            /**
             * Obs1 Deg
             * @description NAV1 OBS course in degrees.
             */
            obs1_deg?: number | null;
            /**
             * Obs2 Deg
             * @description NAV2 OBS course in degrees.
             */
            obs2_deg?: number | null;
            /**
             * Autopilot Master
             * @description True = autopilot servos engaged and flying the aircraft.
             */
            autopilot_master?: boolean | null;
            /**
             * Flight Director
             * @description True = flight director bars shown. Engaging the autopilot implies a flight director; switching the flight director off switches the autopilot off with it.
             */
            flight_director?: boolean | null;
            /**
             * Autopilot Nav
             * @description True = NAV (VOR/LOC/GPS) selected as the lateral mode.
             */
            autopilot_nav?: boolean | null;
            /**
             * Autopilot App
             * @description True = APPROACH selected as the lateral mode.
             */
            autopilot_app?: boolean | null;
            /**
             * Autopilot Hdg
             * @description True = HEADING selected as the lateral mode.
             */
            autopilot_hdg?: boolean | null;
            /**
             * Target Altitude Ft
             * @description Autopilot altitude selector, feet MSL. Not the aircraft's.
             */
            target_altitude_ft?: number | null;
            /**
             * Target Ias Kt
             * @description Autopilot speed selector, indicated knots.
             */
            target_ias_kt?: number | null;
            /**
             * Target Heading Deg
             * @description Autopilot heading bug, MAGNETIC degrees (a heading selector always is).
             */
            target_heading_deg?: number | null;
            /**
             * Target Vertical Speed Fpm
             * @description Autopilot vertical speed selector, feet per minute.
             */
            target_vertical_speed_fpm?: number | null;
        };
        /**
         * AircraftSetupResult
         * @description The outcome of a write: what was asked for, and what the aircraft looks like now.
         *
         *     ``applied`` is echoed back because :class:`~core.models.AircraftState` does
         *     not carry configuration — flaps, gear and lights are invisible in the live
         *     feed, so the panel would have nothing to reconcile them against.
         */
        AircraftSetupResult: {
            /** @description Exactly the setup that was applied. */
            applied: components["schemas"]["AircraftSetup"];
            /** @description The aircraft state after the write. */
            state: components["schemas"]["AircraftState"];
        };
        /**
         * AircraftState
         * @description A live snapshot of the user aircraft, as streamed over the WebSocket.
         */
        AircraftState: {
            /**
             * Latitude
             * @description Degrees, WGS84, positive north.
             */
            latitude: number;
            /**
             * Longitude
             * @description Degrees, WGS84, positive east.
             */
            longitude: number;
            /**
             * Altitude Ft
             * @description Feet above mean sea level.
             */
            altitude_ft: number;
            /**
             * Heading Deg
             * @description True heading in degrees.
             */
            heading_deg: number;
            /**
             * Ias Kt
             * @description Indicated airspeed in knots.
             */
            ias_kt: number;
            /**
             * Vertical Speed Fpm
             * @description Vertical speed in feet per minute.
             */
            vertical_speed_fpm: number;
            /**
             * Pitch Deg
             * @description Pitch in degrees, positive nose up.
             */
            pitch_deg: number;
            /**
             * Roll Deg
             * @description Bank in degrees, positive right wing down.
             */
            roll_deg: number;
            /**
             * On Ground
             * @description True when any gear touches the ground.
             * @default false
             */
            on_ground: boolean;
        };
        /**
         * Capabilities
         * @description What a given adapter supports, as declared by the adapter itself.
         *
         *     All flags default to ``False``: a new capability is unsupported everywhere
         *     until an adapter opts in. This is a pydantic model rather than a plain
         *     dataclass so that it is served verbatim by ``GET /api/capabilities`` and
         *     lands in the OpenAPI schema the UI client is generated from.
         *
         *     Immutable — an adapter's capabilities never change at runtime.
         */
        Capabilities: {
            /**
             * Can Set Position
             * @default false
             */
            can_set_position: boolean;
            /**
             * Can Set Aircraft State
             * @default false
             */
            can_set_aircraft_state: boolean;
            /**
             * Can Set Weather
             * @default false
             */
            can_set_weather: boolean;
            /**
             * Can Inject Failures
             * @default false
             */
            can_inject_failures: boolean;
            /**
             * Can Spawn Traffic
             * @default false
             */
            can_spawn_traffic: boolean;
            /**
             * Can Control Autopilot
             * @default false
             */
            can_control_autopilot: boolean;
            /**
             * Can Set Fuel Payload
             * @default false
             */
            can_set_fuel_payload: boolean;
            /**
             * Can Control Camera
             * @default false
             */
            can_control_camera: boolean;
            /**
             * Can Pushback
             * @default false
             */
            can_pushback: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description ``GET /api/health``.
         *
         *     A declared model rather than a bare ``dict``: the UI client is generated from
         *     this schema, and an untyped dict generates as ``unknown`` on the TypeScript
         *     side, which is exactly the kind of hand-written patching CLAUDE.md forbids.
         */
        HealthResponse: {
            /**
             * Status
             * @description Always "ok" when the process is answering.
             */
            status: string;
            /**
             * Adapter
             * @description Name of the active adapter.
             */
            adapter: string;
            /**
             * Connected
             * @description True when the adapter's link to the simulator is up.
             */
            connected: boolean;
        };
        /**
         * LightsSetup
         * @description Exterior light switches. ``None`` means "leave this switch untouched".
         */
        LightsSetup: {
            /** Landing */
            landing?: boolean | null;
            /** Taxi */
            taxi?: boolean | null;
            /** Nav */
            nav?: boolean | null;
            /** Beacon */
            beacon?: boolean | null;
            /** Strobe */
            strobe?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AircraftState"];
                };
            };
        };
    };
    aircraft_controls_api_aircraft_controls_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AircraftControlManifest"];
                };
            };
        };
    };
    apply_aircraft_setup_api_aircraft_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AircraftSetup"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AircraftSetupResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
